# Generated by Django 4.1.6 on 2023-11-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(db_index=True, default='url_title', max_length=200, verbose_name='نام برند در url'),
            preserve_default=False,
        ),
    ]
