# Generated by Django 4.1.6 on 2023-12-11 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_productvisit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvisit',
            options={'verbose_name': 'بازدید محصول', 'verbose_name_plural': 'بازدیدهای محصول'},
        ),
    ]
