# Generated by Django 4.1.6 on 2024-01-01 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_productcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductComment',
        ),
    ]
