# Generated by Django 4.1.6 on 2023-12-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
    ]
