# Generated by Django 4.1.6 on 2023-09-29 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0004_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2023, 9, 30), verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
    ]
