# Generated by Django 4.1.6 on 2023-11-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0006_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'نظر مقاله', 'verbose_name_plural': 'نظرات مقاله'},
        ),
    ]
